avm2: partially implement Graphics.drawTriangles and drawGraphicsData
ruffle-rs/ruffle pull request #12559
Opened 2023-08-04 23:15 UTC by SuchAFuriousDeath

Progresses #9017 (even seems to make it playable, although the stone texture still looks weird, see the comment I made)
UV mapping, positive and negative culling are unimplemented.

2023-08-04 23:20 UTC, n0samu commented
Welcome, and thank you for contributing! 😃

I'm thinking #9596 could potentially be fixed by this as well!

2023-08-04 23:34 UTC, torokati44 commented
> I'm thinking https://github.com/ruffle-rs/ruffle/issues/9596 could potentially be fixed by this as well!

Almost, but without UV mapping, the textures don't distort together with the mesh. The mesh almost looks like a mask applied to the textures as backgrounds.

2023-08-05 00:23 UTC, n0samu commented
Ah okay, it's a start!

2023-08-05 00:25 UTC, n0samu commented
@SuchAFuriousDeath Can you run `cargo fmt` to fix the test failures?

2023-08-05 00:51 UTC, SuchAFuriousDeath commented
Here you go

2023-08-05 11:56 UTC, Dinnerbone requested changes
Few minor changes. Thank you very much!

2023-08-05 11:56 UTC, Dinnerbone commented on core/src/avm2/globals/flash/display/graphics.rs
> +            let indices = args.get_object(activation, 1, "indices").ok();
```suggestion
            let indices = args.try_get_object(activation, 1);
```

2023-08-05 11:56 UTC, Dinnerbone commented on core/src/avm2/globals/flash/display/graphics.rs
> +            let uvt_data = args.get_object(activation, 2, "uvtData").ok();
```suggestion
            let uvt_data = args.try_get_object(activation, 2);
```

2023-08-05 11:56 UTC, Dinnerbone commented on core/src/avm2/globals/flash/display/graphics.rs
> +        Err(format!("Unknown culling {:?}", culling).into())
```suggestion
        Err(make_error_2008(activation, "culling")
```

2023-08-05 19:43 UTC, SuchAFuriousDeath commented
#9829 looks playable now

2023-08-06 13:53 UTC, SuchAFuriousDeath commented
By the way, just wondering, is there any reason why graphicsshaderfill is not in activation.avm2().classes()? 
https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/GraphicsShaderFill.html

2023-08-07 17:31 UTC, Dinnerbone commented
> By the way, just wondering, is there any reason why graphicsshaderfill is not in activation.avm2().classes()? https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/GraphicsShaderFill.html

Simply because nobody's needed it anywhere, so nobody added it yet.

2023-08-08 00:50 UTC, SuchAFuriousDeath commented
#12022 requires negative culling to be implemented, but unfortunately requires a lot of other functions that are currently stubbed

2023-08-26 10:40 UTC, Dinnerbone approved these changes
Thank you!

2023-08-26 10:57 UTC, merged