web: Adds support for base embed/object attribute (Part of #4258)
ruffle-rs/ruffle pull request #5026
Opened 2021-08-08 20:43 UTC by hatal175

2021-08-08 23:07 UTC, hatal175 commented
I would like to comment that current;y the base value requires to have a slash at the end of the url because of url::parse. I'm not sure what the original flash behavior was.

2021-08-13 22:30 UTC, kmeisthax requested changes
I have one minor nitpick involving spelling on a doc comment, but everything else looks fine.

2021-08-13 22:30 UTC, kmeisthax commented on web/packages/core/src/load-options.ts
> +     * null means the current dirsctory.
spelling: "directory", not "dirsctory"

2021-08-19 19:14 UTC, adrian17 approved these changes
Before merging: did you test this on any specific existing content using this attribute, or did you make your own sample page?

2021-08-19 19:14 UTC, adrian17 commented on web/src/navigator.rs
> +    fn base_uri(&self, document: &Document) -> Option<String> {
Ideally this should probably return a `Cow`, to avoid copying the base_url... but that doesn't really matter much here.

2021-08-19 19:15 UTC, hatal175 commented
Hard to find content so I made my own sample page.

On Thu, Aug 19, 2021, 22:14 Adrian Wielgosik ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Before merging: did you test this on any specific existing content using
> this attribute, or did you make your own sample page?
> ------------------------------
>
> In web/src/navigator.rs
> <https://github.com/ruffle-rs/ruffle/pull/5026#discussion_r692411046>:
>
> > @@ -33,6 +40,17 @@ impl WebNavigatorBackend {
>              performance,
>              allow_script_access,
>              upgrade_to_https,
> +            base_url,
> +        }
> +    }
> +
> +    fn base_uri(&self, document: &Document) -> Option<String> {
>
> Ideally this should probably return a Cow, to avoid copying the
> base_url... but that doesn't really matter much here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ruffle-rs/ruffle/pull/5026#pullrequestreview-734370335>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYQXXL6GHQVNSESAFY5RHTT5VJYJANCNFSM5BY23G2Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-19 19:22 UTC, adrian17 commented
OK.

2021-08-19 19:22 UTC, merged

2021-08-19 19:22 UTC, adrian17 commented
Merged. Thanks!

2021-09-05 04:59 UTC, albertstill commented
Thanks for working on this.

I couldn't actually get it to work in my flash games, I debugged and saw the `base` field being passed into the Ruffle instance here correctly, via `config`, as expected.

https://github.com/ruffle-rs/ruffle/blob/3982f3af9811cfc32c6f7eaf06aa3c8c81b91226/web/packages/core/src/ruffle-player.ts#L417

But it never altered the subsequent swf files my initial swf requested, I could never get the urls to reflect this base property.

Am I expecting the correct behaviour?

I'm using self hosted nightly 2021-09-04 with the polyfill approach.

Thanks

2021-09-05 06:40 UTC, hatal175 commented
Mind sending the html snippet?

On Sun, Sep 5, 2021, 07:59 Albert Still ***@***.***> wrote:

> Thanks for working on this.
>
> I couldn't actually get it to work in my flash games, I debugged and saw
> the base field being passed into the Ruffle instance here correctly, via
> config, as expected.
>
>
> https://github.com/ruffle-rs/ruffle/blob/3982f3af9811cfc32c6f7eaf06aa3c8c81b91226/web/packages/core/src/ruffle-player.ts#L417
>
> But it never altered the subsequent swf files my initial swf requested, I
> could never get the urls to reflect this base property.
>
> Am I expecting the correct behaviour?
>
> I'm using self hosted nightly 2021-09-04 with the polyfill approach.
>
> Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ruffle-rs/ruffle/pull/5026#issuecomment-913086841>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYQXXN5H2ZEEQ3HRNSZDJLUAL2K7ANCNFSM5BY23G2Q>
> .
>

2021-09-06 13:12 UTC, albertstill commented
Thanks @hatal175, here is a [snippet](https://github.com/albertstill/ruffle-base-issue/blob/master/index.html#L13-L29) and repo where you can reproduce this issue, thanks.

https://github.com/albertstill/ruffle-base-issue