core: implement displayState for Stage in avm1/2
ruffle-rs/ruffle pull request #5137
Opened 2021-08-25 08:21 UTC by hatal175

Relevant to several issues (#1562, #4785, #274).

This pull request implements the displayState member for Stage for both avm1 and avm2. I had to rewrite several parts so fullscreen actions would go through the Stage class in core.
I've also implemented the full screen events for both AVMs.
Two issues that I've run into are the following:
1. weird rendering issues in log about extent. It seemed to still go to full screen, so yay.
2. in web, the fullscreen functions are asynchronous. This was happily ignored before and still is but it could cause issues.

2021-08-25 09:16 UTC, hatal175 commented
Not sure what's up with that check. Doesn't seem related to change.

2021-08-25 10:43 UTC, torokati44 commented
I have seen that same check spuriously fail in a different PR as well.
The error message `element ("<ruffle-object />") still not existing after 30000ms` hints that something could have hanged, or possibly there is a race condition?

2021-08-28 19:55 UTC, kmeisthax commented
The error you're getting is a recurring problem with our CI infrastructure. Sometimes the web tests just fail to create the Ruffle element correctly, and we haven't been able to determine why. The solution in every case is to just force the test to run again.

2021-08-29 17:13 UTC, adrian17 commented
A general thing I just noticed in docs:

> Full-screen mode is initiated in response to a mouse click or key press by the user; the movie cannot change Stage.displayState without user input

> While Flash Player is in full-screen mode, all keyboard input is disabled (except keyboard shortcuts that take the user out of full-screen mode). 

I imagine the latter isn't really relevant anymore now that we use "browser fullscreen", but the former sounds reasonable - we probably don't want movies to fullscreen themselves at will? Or do browsers handle that automatically even if there's wasm in the middle?

I'm not saying it's a blocker or obligatory to implement, but that does sound like something we should maybe talk about here or on discord?

As for AVM2 stuff, probably best for kmeisthax to review this.

2021-08-29 18:07 UTC, hatal175 commented
Only within an html page and that's actually enforced by browser.

On Sun, Aug 29, 2021, 20:13 Adrian Wielgosik ***@***.***>
wrote:

> A general thing I just noticed in docs:
>
> Full-screen mode is initiated in response to a mouse click or key press by
> the user; the movie cannot change Stage.displayState without user input
>
> While Flash Player is in full-screen mode, all keyboard input is disabled
> (except keyboard shortcuts that take the user out of full-screen mode).
>
> I imagine the latter isn't really relevant anymore now that we use
> "browser fullscreen", but the former sounds reasonable - we probably don't
> want movies to fullscreen themselves at will? Or do browsers handle that
> automatically even if there's wasm in the middle?
>
> I'm not saying it's a blocker or obligatory to implement, but that does
> sound like something we should maybe talk about here or on discord?
>
> As for AVM2 stuff, probably best for kmeisthax to review this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ruffle-rs/ruffle/pull/5137#issuecomment-907830083>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYQXXIVXWTG6VQQYX3ONRDT7JTDRANCNFSM5CYQSLMQ>
> .
>

2021-08-31 01:20 UTC, kmeisthax requested changes
I have one very minor nitpick, and it's not even with the AVM2 stuff. Everything else seemed straightforward.

2021-08-31 01:20 UTC, kmeisthax commented on core/src/player.rs
> +    pub fn run_context_menu_fullscreen_callback(&mut self, is_fullscreen: bool) {
This should probably be called `set_is_fullscreen`, or `did_enter_fullscreen`, or something. This name is a bit too verbose and less descriptive as to what it does.

2021-09-03 16:50 UTC, danielhjacobs commented
I don't know if you meant to (I see a force push and a review request so I assume you did) but you never changed the name of the method run_context_menu_fullscreen_callback despite marking the conversation as resolved.

2021-09-03 16:52 UTC, hatal175 commented
I might have misunderstood. I thought he talked about the parameter name.
That said, it's pretty much like another context function...

On Fri, Sep 3, 2021, 19:50 Daniel Jacobs ***@***.***> wrote:

> I don't know if you meant to (I see a force push and a review request so I
> assume you did) but you never changed the name of the method
> run_context_menu_fullscreen_callback despite marking the conversation as
> resolved.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ruffle-rs/ruffle/pull/5137#issuecomment-912674567>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYQXXNCGKKPP3EXDVXXHG3UAD4EVANCNFSM5CYQSLMQ>
> .
>

2021-09-03 17:05 UTC, danielhjacobs commented
Yeah, it's consistent with the names @adrian17 gave the functions added in #4173. I can't say I like those names, but it does match what already exists, so perhaps it should be kept. That would be @kmeisthax 's call though.

2021-09-03 17:37 UTC, adrian17 commented
> That said, it's pretty much like another context function...

> Yeah, it's consistent with the names @adrian17 gave the functions added in #4173

Not really. The intention behind `run_context_menu_callback` is to be a single point from context menu item to a callback function attached to it. IMO if we wanted to be consistent with that interface, instead of adding `run_context_menu_fullscreen_callback`, the Fullscreen button should be handled the same way as all other builtin context menu items, and there should be another branch added to the former function, like this:

```rs
ContextMenuCallback::Play => Self::toggle_play_root_movie(context),
ContextMenuCallback::Forward => Self::forward_root_movie(context),
ContextMenuCallback::Back => Self::back_root_movie(context),
ContextMenuCallback::Rewind => Self::rewind_root_movie(context),
ContextMenuCallback::Fullscreen=> Self::toggle_fullscreen(context), // or Enable/DisableFullscreen pair?
```

2021-09-03 22:38 UTC, hatal175 commented
Renamed function.

2021-09-03 23:04 UTC, danielhjacobs commented
> > IMO if we wanted to be consistent with that interface, instead of adding `run_context_menu_fullscreen_callback`, the Fullscreen button should be handled the same way as all other builtin context menu items, and there should be another branch added to the former function

Then it would be hidden by menu="0", and I disagree with doing that personally, as I mentioned here:https://github.com/ruffle-rs/ruffle/issues/4258#issuecomment-864100254

2021-09-03 23:20 UTC, adrian17 commented
IMO, using a single API internally doesn't mean that internal logic can't be changed to always show `Fullscreen`.

Anyway, this can still be done in a separate PR if needed; as for now, the `set_fullscreen` is a nice rename, thanks :)

2021-11-11 05:17 UTC, kmeisthax approved these changes

2021-11-11 05:18 UTC, kmeisthax commented
@hatal175 Sorry for the wait, I'll merge this on the next rebase

2021-11-11 07:03 UTC, ousia commented
Many thanks for the implementation, @hatal175.

2021-11-11 23:20 UTC, merged