web: Add a loading screen
ruffle-rs/ruffle pull request #6839
Opened 2022-04-30 23:10 UTC by Herschel

Add a quick loading screen while the Ruffle WebAssembly loads.

This is a rough first pass loosely based on the custom loading bar on NG by @PsychoGoldfishNG. This really needs someone that is good with CSS to make it more functional and pretty -- I'm not that person! But I at least wanted to get this started.

TODO:
 * Make the loader fluid for very small containers, shrinking/hiding the Ruffle logo as the container shrinks.
 * Add a way to disable or slightly customize the preloader.
 * Get rid of the blue background. This works good for games, but it's not good for content like Flash web sites, which really want to display the native background color of the embed (#1752, #2135). Maybe use a smaller box instead of taking over the entire container.
 * Currently the progress bar only monitors the Wasm downloading, and not the SWF itself -- the progress bar will show as "full" while the SWF starts up. It's at least better than a white screen. We'd have to move the SWF fetch from Rust land to JavaScript to monitor its progress, but probably not worth it since we want to stream the SWF eventually.
 * Even when we have SWF streaming, we'll want the preloader for the wasm download, as it's quite hefty and will only get bigger with time.

2022-05-01 05:01 UTC, relrelb commented on web/packages/core/src/load-ruffle.ts
> +                    for (;;) {
Looks like [`for await..of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of )can be used here.

2022-05-01 05:43 UTC, relrelb commented on web/packages/core/src/load-ruffle.ts
> +        ? new URL("../pkg/ruffle_web_bg.wasm", import.meta.url)
The URLs should be swapped.

2022-05-11 19:19 UTC, danielhjacobs commented
> the progress bar will show as "full" while the SWF starts up

Does it? In my limited testing it seems to not show at all once the WASM has downloaded. A simple way to make it show (without consider for it staying at 100%) would be to move `this.isPreloaderVisible = false;` from the ensureFreshInstance function to the setMetadata function.

2022-05-11 19:31 UTC, danielhjacobs commented
Tested with https://henrystickman.net/content/upload/games/files/fleeing-the-complex.swf

2022-05-16 15:37 UTC, danielhjacobs requested changes

2022-05-16 15:37 UTC, danielhjacobs commented on web/packages/core/src/shadow-template.ts
> +                width: 100%;
width: 60%;

2022-05-16 15:37 UTC, danielhjacobs commented on web/packages/core/src/shadow-template.ts
> +                height: 100%;
height: auto;

2022-05-16 15:37 UTC, danielhjacobs commented on web/packages/core/src/shadow-template.ts
> +            }
aspect-ratio: 2;
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translateX(-50%) translateY(-50%);
    }

2022-05-16 15:37 UTC, danielhjacobs commented on web/packages/core/src/shadow-template.ts
> +                background: var(--ruffle-blue);
background: var(--preloader-background, var(--ruffle-blue));

That way, people who want to use a different background color can add this to the main site's CSS:

```
:root {
    --preloader-background: none; // or different color
}
```

2022-05-16 15:37 UTC, danielhjacobs commented on web/packages/core/src/shadow-template.ts
> +                margin-top: -15px;
margin-top: -3%;

2022-05-16 15:37 UTC, danielhjacobs commented on web/packages/core/src/shadow-template.ts
> +        </style>
.logo {
            	display: var(--logo-display, block);
            }
        </style>
That way, people who don't want to use the Ruffle logo can add this to the main site's CSS:

```
:root {
    --logo-display: none;
}
```

2022-05-16 15:37 UTC, danielhjacobs commented on web/packages/core/src/shadow-template.ts
> +        <svg class="logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid" width="380" height="150"><g><path fill="#966214" d="M58.75 85.6q
`<svg ...  "xMidYMid" viewBox="0 0 380 150" style="max-width: 380px; max-height: 150px; resize: horizontal; width: 100%; height: 100%;"><g><path fill="#966214" ... ><path fill="var(--ruffle-orange)" ... </g></svg>`

2022-05-16 15:48 UTC, danielhjacobs commented on web/packages/core/src/ruffle-player.ts
> +        this.isPreloaderVisible = false;
Move this here: https://github.com/ruffle-rs/ruffle/blob/4f05d1852dd6c8e654aead0dcff7fefbc07264c9/web/packages/core/src/ruffle-player.ts#L1407

2022-07-10 20:31 UTC, Herschel commented
Superseded by #7292.

2022-07-10 20:31 UTC, closed without merging