core: Implement custom UTF-8 handling for dealing with raw bytes
ruffle-rs/ruffle pull request #7420
Opened 2022-07-15 20:59 UTC by EmperorBale

This PR implements a custom UTF-8 decoder for dealing with flash's weird UTF-8 handling. See the comment on `wstr::utils::AvmUtf8Decoder` for detailed information about the difference between how flash decodes UTF-8, and how a regular UTF-8 decoder would decode UTF-8.

As a result of this PR, any code relying `AvmString::new_utf8_bytes` no longer needs to worry about error handling, because why worry about error handling when you can simply just never fail.

For testing, I used a combination of ByteArray & the escape method so I could create the invalid UTF-8 sequences easily, and so that I could easily convert the output to hex for better testing.

2022-07-16 01:01 UTC, moulins requested changes

2022-07-25 04:49 UTC, Herschel commented on wstr/src/utils.rs
> +    dst.push(w2);
`dst.extend_from_slice(&[w1, w2])` ?

2022-07-25 04:52 UTC, Herschel commented
Thank you! LGTM, I'll let @moulins give his approval :-)

2022-07-25 16:33 UTC, moulins approved these changes

2022-07-25 17:52 UTC, merged