core: Always check mergeAlpha in BitmapData.draw
ruffle-rs/ruffle pull request #7912
Opened 2022-09-08 00:56 UTC by Aaron1011

Previously, we would only use mergeAlpha if alphaBitmapData and alphaPoint. However, mergeAlpha can be used even when those parameters are null.

2022-09-08 01:03 UTC, torokati44 commented
I suppose you meant `copyPixels` instead of `draw`?

2022-09-08 01:13 UTC, torokati44 commented
[BitmapCopyPixels.zip](https://github.com/ruffle-rs/ruffle/files/9522644/BitmapCopyPixels.zip)

This is the two figures in the top left corner in Flash Player:
![image](https://user-images.githubusercontent.com/288816/189011799-08f5c1c4-0c1a-4959-8e7b-e2930111017b.png)

And in Ruffle with this change:
![image](https://user-images.githubusercontent.com/288816/189011853-efa3cc89-85f1-430e-83c8-bbb40537f88f.png)

2022-09-08 03:16 UTC, Aaron1011 commented
@torokati44 Thanks! Do you have a .fla available as well?

2022-09-08 03:34 UTC, Aaron1011 commented
It looks like the behavior may be different under AVM1 vs AVM2

2022-09-08 07:03 UTC, torokati44 commented
> Do you have a .fla available as well?

There is no .fla, since I made this test with `mxmlc` only, not with Adobe Flash.
But the AS source is linked in the mentioned PR.

> It looks like the behavior may be different under AVM1 vs AVM2

Uh-oh. 😐

2022-09-09 04:00 UTC, Aaron1011 commented
@torokati44: The issue turned out to be the handling of `mergeDefault` in AVM1 when only three arguments are specified (it appears to default to `false`, but defaults to `true` if five arguments are specified).

There's now a tiny difference in the image output, which is caused by newly-added code that forces the alpha value to 255 for a non-transparent destination image.

2022-09-10 13:04 UTC, torokati44 commented
> (it appears to default to false, but defaults to true if five arguments are specified).

Ah, great. Couldn't have thought of that!

> There's now a tiny difference in the image output

There already was some, and it's still not as bad to cause any real problems IMHO.

2022-09-11 07:18 UTC, Dinnerbone requested changes

2022-09-11 07:18 UTC, Dinnerbone commented on core/src/avm2/globals/flash/display/bitmapdata.rs
> +                        .expect("Missing alpha point!")
We shouldn't panic because we're missing an argument, it should do whatever flash does - return undefined or something?

2022-09-11 07:18 UTC, Dinnerbone commented on core/src/avm2/globals/flash/display/bitmapdata.rs
>                  log::warn!("BitmapData.copyPixels - alpha not implemented");
Is this still true?

2022-09-11 07:42 UTC, Dinnerbone approved these changes

2022-09-11 16:12 UTC, merged