Remove & disallow unwraps in various crates
ruffle-rs/ruffle pull request #8969
Opened 2022-12-31 00:41 UTC by Dinnerbone

Part of the "let's stop panicking" effort. Absolutely not exhaustive for the whole codebase, but this removes all use of unwraps and disallows them going forwards, in the following crates:
- render
- render/webgl
- render/canvas
- web
- desktop
- video

2022-12-31 00:54 UTC, n0samu commented
Looking at the open issues, we have:
- 121 panics related to `navigator.rs`
- 91 panics related to `webgl/src/lib.rs`
- 28 panics related to `canvas/src/lib.rs`
- 14 panics related to `web/src/audio.rs`
It'll be interesting to see how many are resolved by this! On the other hand, I guess it might make it harder to catch related issues since users won't be reporting them as often. I guess we should try to triage more of the ones we have now!

2022-12-31 10:20 UTC, Dinnerbone commented
@n0samu any chance you have a list of (ideally unique) panics per file like that? I can take a look at the causes

2022-12-31 11:11 UTC, adrian17 commented
> On the other hand, I guess it might make it harder to catch related issues since users won't be reporting them as often.

FWIW I agree, some of these like `Couldn't register shape` definitely should be something we should know about. It _could_ just so happen that the shape doesn't happen to be seen by user at any point and the game could otherwise work, yes. But I'd still consider it a more critical error than say `"Tried to instantiate non-registered character ID"`, which AFAIK _can_ happen naturally in the wild.

(Of course, I love the general effort of pushing errors to outside layers and adding context :) )

2022-12-31 11:12 UTC, adrian17 commented
(I'm gonna read through the list more after new year's)

2022-12-31 11:19 UTC, adrian17 commented
> FWIW I agree, some of these like Couldn't register shape definitely should be something we should know about

Update: I just looked at it more, didn't realize that these can only come from GL operation errors. Though... that also made me realize, looks like we currently completely swallow any errors coming from the lyon tessellator :(

2022-12-31 21:49 UTC, Aaron1011 commented on render/webgl/src/lib.rs
> +        .expect("Bitmap handle must be BitmapHandleImpl")
```suggestion
        .expect("Bitmap handle must be webgl RegistryData")
```

2022-12-31 21:49 UTC, Aaron1011 commented on render/canvas/src/lib.rs
> +        .expect("Bitmap handle must be BitmapHandleImpl")
```suggestion
        .expect("Bitmap handle must be canvas BitmapData")
```

2022-12-31 21:51 UTC, Aaron1011 requested changes
A `BitmapHandle` always stores a `BitmapHandleImpl` trait object - the `expect` message should reference the backend-specific type being used as the downcast target.

2022-12-31 22:16 UTC, n0samu commented
> @n0samu any chance you have a list of (ideally unique) panics per file like that? I can take a look at the causes

I don't have a list - I got those numbers by searching the open GitHub issues with the `error-report` label for the filename in question, for example:
`is:open is:issue label:error-report web/src/audio.rs`

2023-01-04 17:08 UTC, Aaron1011 requested changes

2023-01-04 17:08 UTC, Aaron1011 commented on render/src/shape_utils.rs
> +        let first = i.next().expect("Points isn't empty");
```suggestion
        let first = i.next().expect("Points is empty");
```

2023-01-04 17:08 UTC, Aaron1011 commented on scanner/src/execute.rs
> +        .with_navigator(NullNavigatorBackend::with_base_path(base_path, &executor).unwrap())
Should this be an `expect` instead?

2023-01-09 20:47 UTC, Aaron1011 approved these changes

2023-01-10 00:27 UTC, adrian17 commented
(FWIW, my point about swallowing errors in shape registration still stands)

2023-01-10 10:10 UTC, merged