desktop: Improve --help messages
ruffle-rs/ruffle pull request #9364
Opened 2023-01-31 08:17 UTC by n0samu

Mention that SWFs can be loaded via URL as well as file path. And add a listing of the possible values for the `--load-behavior` option.

2023-01-31 10:53 UTC, Dinnerbone requested changes

2023-01-31 10:53 UTC, Dinnerbone commented on core/Cargo.toml
> +clap = { version = "4.1.4", features = ["derive"] }
This should be optional and then enabled by a festure that desktop uses. I think we do this in wgpu create so you can see how it works there

2023-02-02 14:20 UTC, Dinnerbone commented
In core/Cargo.toml, mark clap as optional:
```toml
clap = { version = "4.1.4", features = ["derive"], optional = true }
```

In desktop/Cargo.toml add `"clap"` to the list of features we use from `core`.
```toml
ruffle_core = { path = "../core", features = ["audio", "mp3", "nellymoser", "clap"] }
```

Then change your derive to:
```rust
[cfg_attr(feature = "clap", clap::ValueEnum)]
[derive(Debug, Clone, Copy)]
```

2023-02-03 07:59 UTC, n0samu commented
Thanks! Sorry I didn't have time to figure that out myself yet.

2023-02-03 13:03 UTC, Dinnerbone approved these changes

2023-02-03 20:17 UTC, merged